# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: AmazonWebServices.aws-vsts-tools.AWSPowerShellModuleScript.AWSPowerShellModuleScript@1
  displayName: 'AWS Tools for Windows PowerShell Script: '
  inputs:
    awsCredentials: exams
    regionName: 'us-east-1'
    filePath: '$(System.DefaultWorkingDirectory)/Ridhima1992.devopsexam (1)/EnvironmentSetup.ps1'
- task: MFelling.AWSS3Upload.custom-build-task.S3Upload@0
  displayName: 'Upload file to S3 bucket'
  inputs:
    BucketName: devopsexam


